create table if not exists public.family_leaderboard (
    id bigint generated by default as identity primary key,
    family_id text not null,
    player_id text not null,
    name text not null check (char_length(name) between 1 and 12),
    score integer not null check (score >= 0),
    created_at timestamptz not null default now()
);

create index if not exists family_leaderboard_family_score_idx
on public.family_leaderboard (family_id, score desc, created_at asc);

create index if not exists family_leaderboard_family_player_idx
on public.family_leaderboard (family_id, player_id, score desc);

create or replace function public.normalize_leaderboard_name(value text)
returns text
language sql
immutable
as $$
    select regexp_replace(lower(trim(coalesce(value, ''))), '\s+', ' ', 'g');
$$;

create index if not exists family_leaderboard_family_normalized_name_idx
on public.family_leaderboard (family_id, public.normalize_leaderboard_name(name));

create table if not exists public.family_notifications (
    id bigint generated by default as identity primary key,
    family_id text not null,
    target_player_id text not null,
    challenger_name text not null check (char_length(challenger_name) between 1 and 12),
    challenger_score integer not null check (challenger_score >= 0),
    beaten_score integer not null check (beaten_score >= 0),
    created_at timestamptz not null default now(),
    read_at timestamptz
);

create index if not exists family_notifications_target_idx
on public.family_notifications (family_id, target_player_id, created_at desc);

alter table public.family_leaderboard enable row level security;
alter table public.family_notifications enable row level security;

create policy "family_leaderboard_read"
on public.family_leaderboard
for select
using (true);

create policy "family_leaderboard_insert"
on public.family_leaderboard
for insert
with check (true);

create policy "family_notifications_read"
on public.family_notifications
for select
using (true);

create policy "family_notifications_update"
on public.family_notifications
for update
using (true)
with check (true);

create or replace function public.enforce_unique_leaderboard_names()
returns trigger
language plpgsql
as $$
declare
    existing_player_name text;
    conflicting_player_name text;
begin
    new.name := trim(new.name);

    select name
    into existing_player_name
    from public.family_leaderboard
    where family_id = new.family_id
      and player_id = new.player_id
    order by created_at asc, id asc
    limit 1;

    if existing_player_name is not null then
        new.name := existing_player_name;
        return new;
    end if;

    select name
    into conflicting_player_name
    from public.family_leaderboard
    where family_id = new.family_id
      and player_id <> new.player_id
      and public.normalize_leaderboard_name(name) = public.normalize_leaderboard_name(new.name)
    order by created_at asc, id asc
    limit 1;

    if conflicting_player_name is not null then
        raise exception using
            errcode = '23505',
            message = 'That player name is already taken. Please choose another.';
    end if;

    return new;
end;
$$;

drop trigger if exists family_leaderboard_name_guard on public.family_leaderboard;

create trigger family_leaderboard_name_guard
before insert on public.family_leaderboard
for each row
execute function public.enforce_unique_leaderboard_names();

create or replace function public.notify_family_when_score_beaten()
returns trigger
language plpgsql
as $$
declare
    previous_personal_best integer;
begin
    select max(score)
    into previous_personal_best
    from public.family_leaderboard
    where family_id = new.family_id
      and player_id = new.player_id
      and id <> new.id;

    if previous_personal_best is not null and new.score <= previous_personal_best then
        return new;
    end if;

    insert into public.family_notifications (
        family_id,
        target_player_id,
        challenger_name,
        challenger_score,
        beaten_score
    )
    select
        new.family_id,
        other_scores.player_id,
        new.name,
        new.score,
        other_scores.best_score
    from (
        select player_id, max(score) as best_score
        from public.family_leaderboard
        where family_id = new.family_id
          and player_id <> new.player_id
        group by player_id
    ) as other_scores
    where new.score > other_scores.best_score;

    return new;
end;
$$;

drop trigger if exists family_score_beaten_notification on public.family_leaderboard;

create trigger family_score_beaten_notification
after insert on public.family_leaderboard
for each row
execute function public.notify_family_when_score_beaten();
