create table if not exists public.family_leaderboard (
    id bigint generated by default as identity primary key,
    family_id text not null,
    player_id text not null,
    name text not null check (char_length(name) between 1 and 12),
    score integer not null check (score >= 0),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.family_leaderboard
    add column if not exists updated_at timestamptz not null default now();

with ranked_rows as (
    select
        id,
        row_number() over (
            partition by family_id, player_id
            order by score desc, created_at asc, id asc
        ) as row_rank,
        first_value(created_at) over (
            partition by family_id, player_id
            order by score desc, created_at asc, id asc
        ) as best_achieved_at
    from public.family_leaderboard
)
update public.family_leaderboard as leaderboard_row
set updated_at = ranked_rows.best_achieved_at
from ranked_rows
where leaderboard_row.id = ranked_rows.id
  and ranked_rows.row_rank = 1
  and leaderboard_row.updated_at is distinct from ranked_rows.best_achieved_at;

with ranked_rows as (
    select
        id,
        row_number() over (
            partition by family_id, player_id
            order by score desc, created_at asc, id asc
        ) as row_rank
    from public.family_leaderboard
)
delete from public.family_leaderboard
where id in (
    select id
    from ranked_rows
    where row_rank > 1
);

drop index if exists family_leaderboard_family_player_idx;
create unique index if not exists family_leaderboard_family_player_uidx
on public.family_leaderboard (family_id, player_id);

drop index if exists family_leaderboard_family_score_idx;
create index if not exists family_leaderboard_family_score_idx
on public.family_leaderboard (family_id, score desc, updated_at asc, created_at asc);

create or replace function public.normalize_leaderboard_name(value text)
returns text
language sql
immutable
as $$
    select regexp_replace(lower(trim(coalesce(value, ''))), '\s+', ' ', 'g');
$$;

create extension if not exists pg_net;

create index if not exists family_leaderboard_family_normalized_name_idx
on public.family_leaderboard (family_id, public.normalize_leaderboard_name(name));

create table if not exists public.family_notifications (
    id bigint generated by default as identity primary key,
    family_id text not null,
    target_player_id text not null,
    challenger_name text not null check (char_length(challenger_name) between 1 and 12),
    challenger_score integer not null check (challenger_score >= 0),
    beaten_score integer not null check (beaten_score >= 0),
    created_at timestamptz not null default now(),
    read_at timestamptz
);

create index if not exists family_notifications_target_idx
on public.family_notifications (family_id, target_player_id, created_at desc);

create table if not exists public.family_push_devices (
    id bigint generated by default as identity primary key,
    family_id text not null,
    player_id text not null,
    device_id text not null,
    fcm_token text not null,
    platform text not null default 'android',
    device_label text,
    notifications_enabled boolean not null default true,
    last_seen_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (family_id, player_id, device_id),
    unique (fcm_token)
);

create index if not exists family_push_devices_player_idx
on public.family_push_devices (family_id, player_id, notifications_enabled);

create index if not exists family_push_devices_token_idx
on public.family_push_devices (fcm_token);

create table if not exists public.family_push_delivery_log (
    id bigint generated by default as identity primary key,
    family_id text not null,
    target_player_id text not null,
    device_id text,
    fcm_token text,
    notification_type text not null,
    status text not null,
    response_code integer,
    response_body text,
    created_at timestamptz not null default now()
);

create index if not exists family_push_delivery_log_target_idx
on public.family_push_delivery_log (family_id, target_player_id, created_at desc);

create table if not exists public.family_push_runtime_config (
    id boolean primary key default true check (id),
    enabled boolean not null default false,
    function_url text,
    webhook_secret text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

insert into public.family_push_runtime_config (id)
values (true)
on conflict (id) do nothing;

alter table public.family_leaderboard enable row level security;
alter table public.family_notifications enable row level security;
alter table public.family_push_devices enable row level security;
alter table public.family_push_delivery_log enable row level security;
alter table public.family_push_runtime_config enable row level security;

drop policy if exists "family_leaderboard_read" on public.family_leaderboard;
create policy "family_leaderboard_read"
on public.family_leaderboard
for select
using (true);

drop policy if exists "family_leaderboard_insert" on public.family_leaderboard;
create policy "family_leaderboard_insert"
on public.family_leaderboard
for insert
with check (true);

drop policy if exists "family_leaderboard_update" on public.family_leaderboard;
create policy "family_leaderboard_update"
on public.family_leaderboard
for update
using (true)
with check (true);

drop policy if exists "family_notifications_read" on public.family_notifications;
create policy "family_notifications_read"
on public.family_notifications
for select
using (true);

drop policy if exists "family_notifications_insert" on public.family_notifications;
create policy "family_notifications_insert"
on public.family_notifications
for insert
with check (true);

drop policy if exists "family_notifications_update" on public.family_notifications;
create policy "family_notifications_update"
on public.family_notifications
for update
using (true)
with check (true);

drop policy if exists "family_push_devices_read" on public.family_push_devices;
create policy "family_push_devices_read"
on public.family_push_devices
for select
using (true);

drop policy if exists "family_push_devices_insert" on public.family_push_devices;
create policy "family_push_devices_insert"
on public.family_push_devices
for insert
with check (true);

drop policy if exists "family_push_devices_update" on public.family_push_devices;
create policy "family_push_devices_update"
on public.family_push_devices
for update
using (true)
with check (true);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at := now();
    return new;
end;
$$;

drop trigger if exists family_push_devices_touch_updated_at on public.family_push_devices;

create trigger family_push_devices_touch_updated_at
before update on public.family_push_devices
for each row
execute function public.touch_updated_at();

drop trigger if exists family_push_runtime_config_touch_updated_at on public.family_push_runtime_config;

create trigger family_push_runtime_config_touch_updated_at
before update on public.family_push_runtime_config
for each row
execute function public.touch_updated_at();

drop trigger if exists family_leaderboard_touch_updated_at on public.family_leaderboard;

create trigger family_leaderboard_touch_updated_at
before update on public.family_leaderboard
for each row
execute function public.touch_updated_at();

create or replace function public.enforce_unique_leaderboard_names()
returns trigger
language plpgsql
as $$
declare
    conflicting_player_name text;
begin
    new.name := trim(new.name);

    if tg_op = 'UPDATE' then
        new.name := old.name;
        return new;
    end if;

    select name
    into conflicting_player_name
    from public.family_leaderboard
    where family_id = new.family_id
      and player_id <> new.player_id
      and public.normalize_leaderboard_name(name) = public.normalize_leaderboard_name(new.name)
    order by updated_at asc, created_at asc, id asc
    limit 1;

    if conflicting_player_name is not null then
        raise exception using
            errcode = '23505',
            message = 'That player name is already taken. Please choose another.';
    end if;

    return new;
end;
$$;

drop trigger if exists family_leaderboard_name_guard on public.family_leaderboard;

create trigger family_leaderboard_name_guard
before insert or update on public.family_leaderboard
for each row
execute function public.enforce_unique_leaderboard_names();

create or replace function public.notify_family_when_score_beaten()
returns trigger
language plpgsql
as $$
begin
    if tg_op = 'UPDATE' and new.score <= old.score then
        return new;
    end if;

    insert into public.family_notifications (
        family_id,
        target_player_id,
        challenger_name,
        challenger_score,
        beaten_score
    )
    select
        new.family_id,
        other_scores.player_id,
        new.name,
        new.score,
        other_scores.score
    from public.family_leaderboard as other_scores
    where other_scores.family_id = new.family_id
      and other_scores.player_id <> new.player_id
      and new.score > other_scores.score;

    return new;
end;
$$;

drop trigger if exists family_score_beaten_notification on public.family_leaderboard;

create trigger family_score_beaten_notification
after insert or update on public.family_leaderboard
for each row
execute function public.notify_family_when_score_beaten();

create or replace function public.submit_family_score(
    p_family_id text,
    p_player_id text,
    p_name text,
    p_score integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    leaderboard_row public.family_leaderboard%rowtype;
    score_improved boolean := false;
begin
    if p_family_id is null or trim(p_family_id) = '' then
        raise exception 'Family id is required.';
    end if;

    if p_player_id is null or trim(p_player_id) = '' then
        raise exception 'Player id is required.';
    end if;

    p_name := trim(coalesce(p_name, ''));
    if char_length(p_name) < 1 or char_length(p_name) > 12 then
        raise exception 'Player name must be between 1 and 12 characters.';
    end if;

    if p_score is null or p_score < 0 then
        raise exception 'Score must be zero or higher.';
    end if;

    insert into public.family_leaderboard (
        family_id,
        player_id,
        name,
        score
    )
    values (
        p_family_id,
        p_player_id,
        p_name,
        p_score
    )
    on conflict (family_id, player_id) do update
    set score = excluded.score
    where excluded.score > public.family_leaderboard.score
    returning *
    into leaderboard_row;

    if found then
        score_improved := true;
    else
        select *
        into leaderboard_row
        from public.family_leaderboard
        where family_id = p_family_id
          and player_id = p_player_id
        limit 1;
    end if;

    return jsonb_build_object(
        'player_id', leaderboard_row.player_id,
        'name', leaderboard_row.name,
        'best_score', leaderboard_row.score,
        'score_improved', score_improved,
        'created_at', leaderboard_row.created_at,
        'updated_at', leaderboard_row.updated_at
    );
end;
$$;

grant execute on function public.submit_family_score(text, text, text, integer) to anon, authenticated;

create or replace function public.invoke_score_beaten_push()
returns trigger
language plpgsql
security definer
set search_path = public, net
as $$
declare
    config_row public.family_push_runtime_config%rowtype;
    push_payload jsonb;
    push_headers jsonb;
begin
    select *
    into config_row
    from public.family_push_runtime_config
    where id = true;

    if config_row is null or not config_row.enabled or coalesce(config_row.function_url, '') = '' then
        return new;
    end if;

    push_payload := jsonb_build_object(
        'type', 'score_beaten',
        'family_id', new.family_id,
        'target_player_id', new.target_player_id,
        'challenger_name', new.challenger_name,
        'challenger_score', new.challenger_score,
        'beaten_score', new.beaten_score,
        'created_at', new.created_at
    );

    push_headers := jsonb_build_object(
        'Content-Type', 'application/json'
    );

    if coalesce(config_row.webhook_secret, '') <> '' then
        push_headers := push_headers || jsonb_build_object(
            'x-push-webhook-secret', config_row.webhook_secret
        );
    end if;

    perform net.http_post(
        url := config_row.function_url,
        headers := push_headers,
        body := push_payload
    );

    return new;
exception
    when others then
        insert into public.family_push_delivery_log (
            family_id,
            target_player_id,
            notification_type,
            status,
            response_body
        )
        values (
            new.family_id,
            new.target_player_id,
            'score_beaten',
            'dispatch_error',
            sqlerrm
        );
        return new;
end;
$$;

drop trigger if exists family_notifications_push_dispatch on public.family_notifications;

create trigger family_notifications_push_dispatch
after insert on public.family_notifications
for each row
execute function public.invoke_score_beaten_push();
