alter table public.family_leaderboard
add column if not exists run_summary jsonb not null default '{}'::jsonb,
add column if not exists equipped_skin_id text,
add column if not exists time_survived numeric not null default 0,
add column if not exists missiles_fired integer not null default 0,
add column if not exists hostiles_destroyed integer not null default 0,
add column if not exists ammo_pickups_collected integer not null default 0,
add column if not exists glowing_rocks_triggered integer not null default 0,
add column if not exists boundary_bounces integer not null default 0,
add column if not exists near_misses integer not null default 0,
add column if not exists hostile_near_misses integer not null default 0,
add column if not exists projectile_near_misses integer not null default 0,
add column if not exists skill_score integer not null default 0,
add column if not exists max_combo_multiplier numeric not null default 1,
add column if not exists max_combo_events integer not null default 0,
add column if not exists missile_hits integer not null default 0,
add column if not exists missile_misses integer not null default 0,
add column if not exists max_missile_hit_streak integer not null default 0,
add column if not exists projectile_intercepts integer not null default 0;

alter table public.family_push_devices
add column if not exists daily_missions_enabled boolean not null default true;

create table if not exists public.family_player_profiles (
	id bigint generated by default as identity primary key,
	family_id text not null,
	player_id text not null,
	name text,
	equipped_skin_id text not null default 'default_scout',
	unlocked_skins jsonb not null default '["default_scout"]'::jsonb,
	total_daily_missions_completed integer not null default 0,
	daily_streak integer not null default 0,
	last_completed_daily_date text,
	daily_reminders_enabled boolean not null default true,
	profile_summary jsonb not null default '{}'::jsonb,
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now(),
	unique (family_id, player_id)
);

create table if not exists public.family_daily_mission_progress (
	id bigint generated by default as identity primary key,
	family_id text not null,
	player_id text not null,
	mission_date text not null,
	missions jsonb not null default '[]'::jsonb,
	completed_count integer not null default 0,
	total_count integer not null default 3,
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now(),
	unique (family_id, player_id, mission_date)
);

create table if not exists public.family_run_history (
	id bigint generated by default as identity primary key,
	family_id text not null,
	player_id text not null,
	name text,
	score integer not null check (score >= 0),
	run_summary jsonb not null default '{}'::jsonb,
	equipped_skin_id text,
	created_at timestamptz not null default now()
);

create table if not exists public.family_daily_dispatch_log (
	id bigint generated by default as identity primary key,
	family_id text not null,
	mission_date text not null,
	notification_type text not null default 'daily_missions',
	created_at timestamptz not null default now(),
	unique (family_id, mission_date, notification_type)
);

create index if not exists family_player_profiles_player_idx
on public.family_player_profiles (family_id, player_id);

create index if not exists family_daily_mission_progress_player_date_idx
on public.family_daily_mission_progress (family_id, player_id, mission_date);

create index if not exists family_run_history_player_created_idx
on public.family_run_history (family_id, player_id, created_at desc);

create index if not exists family_run_history_family_score_idx
on public.family_run_history (family_id, score desc, created_at desc);

create index if not exists family_daily_dispatch_log_date_idx
on public.family_daily_dispatch_log (family_id, mission_date, created_at desc);

alter table public.family_player_profiles enable row level security;
alter table public.family_daily_mission_progress enable row level security;
alter table public.family_run_history enable row level security;
alter table public.family_daily_dispatch_log enable row level security;

drop policy if exists "family_player_profiles_read" on public.family_player_profiles;
create policy "family_player_profiles_read"
on public.family_player_profiles
for select
using (true);

drop policy if exists "family_daily_mission_progress_read" on public.family_daily_mission_progress;
create policy "family_daily_mission_progress_read"
on public.family_daily_mission_progress
for select
using (true);

drop policy if exists "family_run_history_read" on public.family_run_history;
create policy "family_run_history_read"
on public.family_run_history
for select
using (true);

drop policy if exists "family_daily_dispatch_log_read" on public.family_daily_dispatch_log;
create policy "family_daily_dispatch_log_read"
on public.family_daily_dispatch_log
for select
using (true);

drop trigger if exists family_player_profiles_touch_updated_at on public.family_player_profiles;
create trigger family_player_profiles_touch_updated_at
before update on public.family_player_profiles
for each row
execute function public.touch_updated_at();

drop trigger if exists family_daily_mission_progress_touch_updated_at on public.family_daily_mission_progress;
create trigger family_daily_mission_progress_touch_updated_at
before update on public.family_daily_mission_progress
for each row
execute function public.touch_updated_at();

create or replace function public.submit_family_score_v2(
	p_family_id text,
	p_player_id text,
	p_name text,
	p_score integer,
	p_run_summary jsonb default '{}'::jsonb,
	p_equipped_skin_id text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
	leaderboard_row public.family_leaderboard%rowtype;
	score_improved boolean := false;
begin
	if p_family_id is null or trim(p_family_id) = '' then
		raise exception 'Family id is required.';
	end if;

	if p_player_id is null or trim(p_player_id) = '' then
		raise exception 'Player id is required.';
	end if;

	p_name := trim(coalesce(p_name, ''));
	if char_length(p_name) < 1 or char_length(p_name) > 12 then
		raise exception 'Player name must be between 1 and 12 characters.';
	end if;

	if p_score is null or p_score < 0 then
		raise exception 'Score must be zero or higher.';
	end if;

	insert into public.family_leaderboard (
		family_id,
		player_id,
		name,
		score,
		run_summary,
		equipped_skin_id,
		time_survived,
		missiles_fired,
		hostiles_destroyed,
		ammo_pickups_collected,
		glowing_rocks_triggered,
		boundary_bounces,
		near_misses,
		hostile_near_misses,
		projectile_near_misses,
		skill_score,
		max_combo_multiplier,
		max_combo_events,
		missile_hits,
		missile_misses,
		max_missile_hit_streak,
		projectile_intercepts
	)
	values (
		p_family_id,
		p_player_id,
		p_name,
		p_score,
		coalesce(p_run_summary, '{}'::jsonb),
		p_equipped_skin_id,
		coalesce((p_run_summary->>'time_survived_seconds')::numeric, 0),
		coalesce((p_run_summary->>'missiles_fired')::integer, 0),
		coalesce((p_run_summary->>'hostiles_destroyed')::integer, 0),
		coalesce((p_run_summary->>'ammo_pickups_collected')::integer, 0),
		coalesce((p_run_summary->>'glowing_rocks_triggered')::integer, 0),
		coalesce((p_run_summary->>'boundary_bounces')::integer, 0),
		coalesce((p_run_summary->>'near_misses')::integer, 0),
		coalesce((p_run_summary->>'hostile_near_misses')::integer, 0),
		coalesce((p_run_summary->>'projectile_near_misses')::integer, 0),
		coalesce((p_run_summary->>'skill_score')::integer, 0),
		coalesce((p_run_summary->>'max_combo_multiplier')::numeric, 1),
		coalesce((p_run_summary->>'max_combo_events')::integer, 0),
		coalesce((p_run_summary->>'missile_hits')::integer, 0),
		coalesce((p_run_summary->>'missile_misses')::integer, 0),
		coalesce((p_run_summary->>'max_missile_hit_streak')::integer, 0),
		coalesce((p_run_summary->>'projectile_intercepts')::integer, 0)
	)
	on conflict (family_id, player_id)
	do update set
		name = excluded.name,
		score = excluded.score,
		run_summary = excluded.run_summary,
		equipped_skin_id = excluded.equipped_skin_id,
		time_survived = excluded.time_survived,
		missiles_fired = excluded.missiles_fired,
		hostiles_destroyed = excluded.hostiles_destroyed,
		ammo_pickups_collected = excluded.ammo_pickups_collected,
		glowing_rocks_triggered = excluded.glowing_rocks_triggered,
		boundary_bounces = excluded.boundary_bounces,
		near_misses = excluded.near_misses,
		hostile_near_misses = excluded.hostile_near_misses,
		projectile_near_misses = excluded.projectile_near_misses,
		skill_score = excluded.skill_score,
		max_combo_multiplier = excluded.max_combo_multiplier,
		max_combo_events = excluded.max_combo_events,
		missile_hits = excluded.missile_hits,
		missile_misses = excluded.missile_misses,
		max_missile_hit_streak = excluded.max_missile_hit_streak,
		projectile_intercepts = excluded.projectile_intercepts,
		updated_at = now()
	where excluded.score > public.family_leaderboard.score
	returning *
	into leaderboard_row;

	if found then
		score_improved := true;
	else
		select *
		into leaderboard_row
		from public.family_leaderboard
		where family_id = p_family_id
		  and player_id = p_player_id
		limit 1;
	end if;

	insert into public.family_run_history (
		family_id,
		player_id,
		name,
		score,
		run_summary,
		equipped_skin_id
	)
	values (
		p_family_id,
		p_player_id,
		p_name,
		p_score,
		coalesce(p_run_summary, '{}'::jsonb),
		p_equipped_skin_id
	);

	return jsonb_build_object(
		'player_id', leaderboard_row.player_id,
		'name', leaderboard_row.name,
		'best_score', leaderboard_row.score,
		'score_improved', score_improved,
		'run_summary', leaderboard_row.run_summary,
		'equipped_skin_id', leaderboard_row.equipped_skin_id,
		'created_at', leaderboard_row.created_at,
		'updated_at', leaderboard_row.updated_at
	);
end;
$$;

grant execute on function public.submit_family_score_v2(text, text, text, integer, jsonb, text)
to anon, authenticated;

create or replace function public.sync_player_profile(
	p_family_id text,
	p_player_id text,
	p_name text default null,
	p_equipped_skin_id text default 'default_scout',
	p_unlocked_skins jsonb default '["default_scout"]'::jsonb,
	p_total_daily_missions_completed integer default 0,
	p_daily_streak integer default 0,
	p_last_completed_daily_date text default null,
	p_daily_reminders_enabled boolean default true,
	p_profile_summary jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
	profile_row public.family_player_profiles%rowtype;
begin
	if p_family_id is null or trim(p_family_id) = '' then
		raise exception 'Family id is required.';
	end if;

	if p_player_id is null or trim(p_player_id) = '' then
		raise exception 'Player id is required.';
	end if;

	insert into public.family_player_profiles (
		family_id,
		player_id,
		name,
		equipped_skin_id,
		unlocked_skins,
		total_daily_missions_completed,
		daily_streak,
		last_completed_daily_date,
		daily_reminders_enabled,
		profile_summary
	)
	values (
		p_family_id,
		p_player_id,
		nullif(trim(coalesce(p_name, '')), ''),
		coalesce(nullif(p_equipped_skin_id, ''), 'default_scout'),
		coalesce(p_unlocked_skins, '["default_scout"]'::jsonb),
		greatest(coalesce(p_total_daily_missions_completed, 0), 0),
		greatest(coalesce(p_daily_streak, 0), 0),
		p_last_completed_daily_date,
		coalesce(p_daily_reminders_enabled, true),
		coalesce(p_profile_summary, '{}'::jsonb)
	)
	on conflict (family_id, player_id)
	do update set
		name = coalesce(excluded.name, public.family_player_profiles.name),
		equipped_skin_id = excluded.equipped_skin_id,
		unlocked_skins = excluded.unlocked_skins,
		total_daily_missions_completed = greatest(
			public.family_player_profiles.total_daily_missions_completed,
			excluded.total_daily_missions_completed
		),
		daily_streak = greatest(
			public.family_player_profiles.daily_streak,
			excluded.daily_streak
		),
		last_completed_daily_date = coalesce(
			excluded.last_completed_daily_date,
			public.family_player_profiles.last_completed_daily_date
		),
		daily_reminders_enabled = excluded.daily_reminders_enabled,
		profile_summary = excluded.profile_summary,
		updated_at = now()
	returning *
	into profile_row;

	return jsonb_build_object(
		'player_id', profile_row.player_id,
		'equipped_skin_id', profile_row.equipped_skin_id,
		'unlocked_skins', profile_row.unlocked_skins,
		'total_daily_missions_completed', profile_row.total_daily_missions_completed,
		'daily_streak', profile_row.daily_streak,
		'last_completed_daily_date', profile_row.last_completed_daily_date,
		'daily_reminders_enabled', profile_row.daily_reminders_enabled,
		'profile_summary', profile_row.profile_summary,
		'updated_at', profile_row.updated_at
	);
end;
$$;

grant execute on function public.sync_player_profile(text, text, text, text, jsonb, integer, integer, text, boolean, jsonb)
to anon, authenticated;

create or replace function public.sync_daily_mission_progress(
	p_family_id text,
	p_player_id text,
	p_mission_date text,
	p_missions jsonb,
	p_completed_count integer,
	p_total_count integer default 3
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
	progress_row public.family_daily_mission_progress%rowtype;
begin
	if p_family_id is null or trim(p_family_id) = '' then
		raise exception 'Family id is required.';
	end if;

	if p_player_id is null or trim(p_player_id) = '' then
		raise exception 'Player id is required.';
	end if;

	if p_mission_date is null or trim(p_mission_date) = '' then
		raise exception 'Mission date is required.';
	end if;

	insert into public.family_daily_mission_progress (
		family_id,
		player_id,
		mission_date,
		missions,
		completed_count,
		total_count
	)
	values (
		p_family_id,
		p_player_id,
		p_mission_date,
		coalesce(p_missions, '[]'::jsonb),
		greatest(coalesce(p_completed_count, 0), 0),
		greatest(coalesce(p_total_count, 3), 1)
	)
	on conflict (family_id, player_id, mission_date)
	do update set
		missions = excluded.missions,
		completed_count = greatest(
			public.family_daily_mission_progress.completed_count,
			excluded.completed_count
		),
		total_count = excluded.total_count,
		updated_at = now()
	returning *
	into progress_row;

	return jsonb_build_object(
		'mission_date', progress_row.mission_date,
		'missions', progress_row.missions,
		'completed_count', progress_row.completed_count,
		'total_count', progress_row.total_count,
		'updated_at', progress_row.updated_at
	);
end;
$$;

grant execute on function public.sync_daily_mission_progress(text, text, text, jsonb, integer, integer)
to anon, authenticated;

create or replace function public.get_player_profile(
	p_family_id text,
	p_player_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
	profile_row public.family_player_profiles%rowtype;
begin
	select *
	into profile_row
	from public.family_player_profiles
	where family_id = p_family_id
	  and player_id = p_player_id
	limit 1;

	if not found then
		return '{}'::jsonb;
	end if;

	return jsonb_build_object(
		'player_id', profile_row.player_id,
		'equipped_skin_id', profile_row.equipped_skin_id,
		'unlocked_skins', profile_row.unlocked_skins,
		'total_daily_missions_completed', profile_row.total_daily_missions_completed,
		'daily_streak', profile_row.daily_streak,
		'last_completed_daily_date', profile_row.last_completed_daily_date,
		'daily_reminders_enabled', profile_row.daily_reminders_enabled,
		'profile_summary', profile_row.profile_summary,
		'updated_at', profile_row.updated_at
	);
end;
$$;

grant execute on function public.get_player_profile(text, text)
to anon, authenticated;

create or replace function public.get_daily_mission_progress(
	p_family_id text,
	p_player_id text,
	p_mission_date text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
	progress_row public.family_daily_mission_progress%rowtype;
begin
	select *
	into progress_row
	from public.family_daily_mission_progress
	where family_id = p_family_id
	  and player_id = p_player_id
	  and mission_date = p_mission_date
	limit 1;

	if not found then
		return '{}'::jsonb;
	end if;

	return jsonb_build_object(
		'mission_date', progress_row.mission_date,
		'missions', progress_row.missions,
		'completed_count', progress_row.completed_count,
		'total_count', progress_row.total_count,
		'updated_at', progress_row.updated_at
	);
end;
$$;

grant execute on function public.get_daily_mission_progress(text, text, text)
to anon, authenticated;
