create table if not exists public.family_leaderboard (
    id bigint generated by default as identity primary key,
    family_id text not null,
    player_id text not null,
    name text not null check (char_length(name) between 1 and 12),
    score integer not null check (score >= 0),
    created_at timestamptz not null default now()
);

create index if not exists family_leaderboard_family_score_idx
on public.family_leaderboard (family_id, score desc, created_at asc);

create index if not exists family_leaderboard_family_player_idx
on public.family_leaderboard (family_id, player_id, score desc);

create or replace function public.normalize_leaderboard_name(value text)
returns text
language sql
immutable
as $$
    select regexp_replace(lower(trim(coalesce(value, ''))), '\s+', ' ', 'g');
$$;

create extension if not exists pg_net;

create index if not exists family_leaderboard_family_normalized_name_idx
on public.family_leaderboard (family_id, public.normalize_leaderboard_name(name));

create table if not exists public.family_notifications (
    id bigint generated by default as identity primary key,
    family_id text not null,
    target_player_id text not null,
    challenger_name text not null check (char_length(challenger_name) between 1 and 12),
    challenger_score integer not null check (challenger_score >= 0),
    beaten_score integer not null check (beaten_score >= 0),
    created_at timestamptz not null default now(),
    read_at timestamptz
);

create index if not exists family_notifications_target_idx
on public.family_notifications (family_id, target_player_id, created_at desc);

create table if not exists public.family_push_devices (
    id bigint generated by default as identity primary key,
    family_id text not null,
    player_id text not null,
    device_id text not null,
    fcm_token text not null,
    platform text not null default 'android',
    device_label text,
    notifications_enabled boolean not null default true,
    last_seen_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (family_id, player_id, device_id),
    unique (fcm_token)
);

create index if not exists family_push_devices_player_idx
on public.family_push_devices (family_id, player_id, notifications_enabled);

create index if not exists family_push_devices_token_idx
on public.family_push_devices (fcm_token);

create table if not exists public.family_push_delivery_log (
    id bigint generated by default as identity primary key,
    family_id text not null,
    target_player_id text not null,
    device_id text,
    fcm_token text,
    notification_type text not null,
    status text not null,
    response_code integer,
    response_body text,
    created_at timestamptz not null default now()
);

create index if not exists family_push_delivery_log_target_idx
on public.family_push_delivery_log (family_id, target_player_id, created_at desc);

create table if not exists public.family_push_runtime_config (
    id boolean primary key default true check (id),
    enabled boolean not null default false,
    function_url text,
    webhook_secret text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

insert into public.family_push_runtime_config (id)
values (true)
on conflict (id) do nothing;

alter table public.family_leaderboard enable row level security;
alter table public.family_notifications enable row level security;
alter table public.family_push_devices enable row level security;
alter table public.family_push_delivery_log enable row level security;
alter table public.family_push_runtime_config enable row level security;

drop policy if exists "family_leaderboard_read" on public.family_leaderboard;
create policy "family_leaderboard_read"
on public.family_leaderboard
for select
using (true);

drop policy if exists "family_leaderboard_insert" on public.family_leaderboard;
create policy "family_leaderboard_insert"
on public.family_leaderboard
for insert
with check (true);

drop policy if exists "family_notifications_read" on public.family_notifications;
create policy "family_notifications_read"
on public.family_notifications
for select
using (true);

drop policy if exists "family_notifications_insert" on public.family_notifications;
create policy "family_notifications_insert"
on public.family_notifications
for insert
with check (true);

drop policy if exists "family_notifications_update" on public.family_notifications;
create policy "family_notifications_update"
on public.family_notifications
for update
using (true)
with check (true);

drop policy if exists "family_push_devices_read" on public.family_push_devices;
create policy "family_push_devices_read"
on public.family_push_devices
for select
using (true);

drop policy if exists "family_push_devices_insert" on public.family_push_devices;
create policy "family_push_devices_insert"
on public.family_push_devices
for insert
with check (true);

drop policy if exists "family_push_devices_update" on public.family_push_devices;
create policy "family_push_devices_update"
on public.family_push_devices
for update
using (true)
with check (true);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at := now();
    return new;
end;
$$;

drop trigger if exists family_push_devices_touch_updated_at on public.family_push_devices;

create trigger family_push_devices_touch_updated_at
before update on public.family_push_devices
for each row
execute function public.touch_updated_at();

drop trigger if exists family_push_runtime_config_touch_updated_at on public.family_push_runtime_config;

create trigger family_push_runtime_config_touch_updated_at
before update on public.family_push_runtime_config
for each row
execute function public.touch_updated_at();

create or replace function public.enforce_unique_leaderboard_names()
returns trigger
language plpgsql
as $$
declare
    existing_player_name text;
    conflicting_player_name text;
begin
    new.name := trim(new.name);

    select name
    into existing_player_name
    from public.family_leaderboard
    where family_id = new.family_id
      and player_id = new.player_id
    order by created_at asc, id asc
    limit 1;

    if existing_player_name is not null then
        new.name := existing_player_name;
        return new;
    end if;

    select name
    into conflicting_player_name
    from public.family_leaderboard
    where family_id = new.family_id
      and player_id <> new.player_id
      and public.normalize_leaderboard_name(name) = public.normalize_leaderboard_name(new.name)
    order by created_at asc, id asc
    limit 1;

    if conflicting_player_name is not null then
        raise exception using
            errcode = '23505',
            message = 'That player name is already taken. Please choose another.';
    end if;

    return new;
end;
$$;

drop trigger if exists family_leaderboard_name_guard on public.family_leaderboard;

create trigger family_leaderboard_name_guard
before insert on public.family_leaderboard
for each row
execute function public.enforce_unique_leaderboard_names();

create or replace function public.notify_family_when_score_beaten()
returns trigger
language plpgsql
as $$
declare
    previous_personal_best integer;
begin
    select max(score)
    into previous_personal_best
    from public.family_leaderboard
    where family_id = new.family_id
      and player_id = new.player_id
      and id <> new.id;

    if previous_personal_best is not null and new.score <= previous_personal_best then
        return new;
    end if;

    insert into public.family_notifications (
        family_id,
        target_player_id,
        challenger_name,
        challenger_score,
        beaten_score
    )
    select
        new.family_id,
        other_scores.player_id,
        new.name,
        new.score,
        other_scores.best_score
    from (
        select player_id, max(score) as best_score
        from public.family_leaderboard
        where family_id = new.family_id
          and player_id <> new.player_id
        group by player_id
    ) as other_scores
    where new.score > other_scores.best_score;

    return new;
end;
$$;

drop trigger if exists family_score_beaten_notification on public.family_leaderboard;

create trigger family_score_beaten_notification
after insert on public.family_leaderboard
for each row
execute function public.notify_family_when_score_beaten();

create or replace function public.invoke_score_beaten_push()
returns trigger
language plpgsql
security definer
set search_path = public, net
as $$
declare
    config_row public.family_push_runtime_config%rowtype;
    push_payload jsonb;
    push_headers jsonb;
begin
    select *
    into config_row
    from public.family_push_runtime_config
    where id = true;

    if config_row is null or not config_row.enabled or coalesce(config_row.function_url, '') = '' then
        return new;
    end if;

    push_payload := jsonb_build_object(
        'type', 'score_beaten',
        'family_id', new.family_id,
        'target_player_id', new.target_player_id,
        'challenger_name', new.challenger_name,
        'challenger_score', new.challenger_score,
        'beaten_score', new.beaten_score,
        'created_at', new.created_at
    );

    push_headers := jsonb_build_object(
        'Content-Type', 'application/json'
    );

    if coalesce(config_row.webhook_secret, '') <> '' then
        push_headers := push_headers || jsonb_build_object(
            'x-push-webhook-secret', config_row.webhook_secret
        );
    end if;

    perform net.http_post(
        url := config_row.function_url,
        headers := push_headers,
        body := push_payload
    );

    return new;
exception
    when others then
        insert into public.family_push_delivery_log (
            family_id,
            target_player_id,
            notification_type,
            status,
            response_body
        )
        values (
            new.family_id,
            new.target_player_id,
            'score_beaten',
            'dispatch_error',
            sqlerrm
        );
        return new;
end;
$$;

drop trigger if exists family_notifications_push_dispatch on public.family_notifications;

create trigger family_notifications_push_dispatch
after insert on public.family_notifications
for each row
execute function public.invoke_score_beaten_push();
