create table if not exists public.client_error_events (
	id bigint generated by default as identity primary key,
	fingerprint text not null,
	severity text not null check (severity in ('debug', 'info', 'warning', 'error', 'fatal')),
	category text not null,
	message text not null,
	context jsonb not null default '{}'::jsonb,
	build jsonb not null default '{}'::jsonb,
	runtime jsonb not null default '{}'::jsonb,
	reported_at timestamptz not null default now(),
	emailed_at timestamptz
);

create index if not exists client_error_events_fingerprint_idx
on public.client_error_events (fingerprint, reported_at desc);

create table if not exists public.family_feedback_reports (
	id bigint generated by default as identity primary key,
	category text not null,
	message text not null,
	bug_report text,
	context jsonb not null default '{}'::jsonb,
	created_at timestamptz not null default now()
);

create index if not exists family_feedback_reports_created_idx
on public.family_feedback_reports (created_at desc);

alter table public.client_error_events enable row level security;
alter table public.family_feedback_reports enable row level security;

drop policy if exists "client_error_events_insert" on public.client_error_events;
create policy "client_error_events_insert"
on public.client_error_events
for insert
with check (true);

drop policy if exists "client_error_events_read" on public.client_error_events;
create policy "client_error_events_read"
on public.client_error_events
for select
using (true);

drop policy if exists "family_feedback_reports_insert" on public.family_feedback_reports;
create policy "family_feedback_reports_insert"
on public.family_feedback_reports
for insert
with check (true);

drop policy if exists "family_feedback_reports_read" on public.family_feedback_reports;
create policy "family_feedback_reports_read"
on public.family_feedback_reports
for select
using (true);
