create table if not exists public.app_release_channels (
	channel text primary key,
	latest_version_code integer not null,
	latest_version_name text not null,
	minimum_supported_version_code integer not null,
	apk_download_url text not null,
	release_page_url text not null,
	release_notes_url text not null,
	update_message text not null default 'A new build is ready.',
	force_update_message text not null default 'This version is too old to play. Please update to continue.',
	release_summary text,
	checksum_sha256 text,
	apk_size_bytes bigint,
	build_sha text,
	release_metadata jsonb not null default '{}'::jsonb,
	updated_at timestamptz not null default now()
);

create table if not exists public.app_update_push_history (
	id bigint generated by default as identity primary key,
	channel text not null,
	version_code integer not null,
	family_id text not null default 'global',
	player_id text,
	device_id text not null,
	status text not null default 'sent',
	created_at timestamptz not null default now(),
	unique (channel, version_code, device_id)
);

create table if not exists public.family_weekly_recap_log (
	id bigint generated by default as identity primary key,
	family_id text not null default 'global',
	week_key text not null,
	status text not null default 'sent',
	created_at timestamptz not null default now(),
	unique (family_id, week_key)
);

alter table public.family_push_devices
add column if not exists app_version_code integer,
add column if not exists app_version_name text,
add column if not exists build_sha text,
add column if not exists release_channel text not null default 'stable';

create index if not exists family_push_devices_release_channel_idx
on public.family_push_devices (release_channel, notifications_enabled, app_version_code);

create or replace view public.family_app_version_adoption as
select
	app_version_code,
	app_version_name,
	release_channel,
	count(*) as device_count,
	max(last_seen_at) as last_seen_at
from public.family_push_devices
group by app_version_code, app_version_name, release_channel;

alter table public.app_release_channels enable row level security;
alter table public.app_update_push_history enable row level security;
alter table public.family_weekly_recap_log enable row level security;

drop policy if exists "app_release_channels_read" on public.app_release_channels;
create policy "app_release_channels_read"
on public.app_release_channels
for select
using (true);

drop policy if exists "app_update_push_history_read" on public.app_update_push_history;
create policy "app_update_push_history_read"
on public.app_update_push_history
for select
using (true);

drop policy if exists "family_weekly_recap_log_read" on public.family_weekly_recap_log;
create policy "family_weekly_recap_log_read"
on public.family_weekly_recap_log
for select
using (true);
